package main;

import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

import analisis.*;
import anasintactico.*;
import java.util.ArrayList;
import javax.swing.*;
import archivo.*;
import java.io.File;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Interfaz extends javax.swing.JFrame {

    JFileChooser seleccionado = new JFileChooser();
    File archivo;
    GestionArchivos gestion = new GestionArchivos();
    ArrayList<Token> lista_token = new ArrayList<>();
    ArrayList<Simbolos> lista_simbolos = new ArrayList<>();
    ArrayList<Bloques> lista_bloques = new ArrayList<>();
    ColorTable cote = new ColorTable();
    java.awt.Color black = java.awt.Color.black;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        setFontSize(15);
        Tabla_Bloque.getColumnModel().getColumn(1).setCellRenderer(new MultiLineTableCellRenderer());
    }

    private void setFontSize(int size) {
        SimpleAttributeSet attr = new SimpleAttributeSet();
        StyleConstants.setFontSize(attr, size);
        text_editor.setCharacterAttributes(attr, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFondo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_sinta = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaToken = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_editor = new javax.swing.JTextPane();
        BTlimpiar = new javax.swing.JButton();
        BT_anasintactico = new javax.swing.JButton();
        BT_analizar = new javax.swing.JButton();
        BT_abrir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla_Bloque = new javax.swing.JTable();
        BT_Crear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JFondo.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ANALIZADOR SINTACTICO");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ANALIZADOR LEXICO");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PARSER-PY");

        table_sinta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Simbolos", "Error", "Linea", "columna"
            }
        ));
        jScrollPane4.setViewportView(table_sinta);
        if (table_sinta.getColumnModel().getColumnCount() > 0) {
            table_sinta.getColumnModel().getColumn(0).setMinWidth(120);
            table_sinta.getColumnModel().getColumn(0).setPreferredWidth(120);
            table_sinta.getColumnModel().getColumn(0).setMaxWidth(120);
            table_sinta.getColumnModel().getColumn(2).setMinWidth(180);
            table_sinta.getColumnModel().getColumn(2).setPreferredWidth(180);
            table_sinta.getColumnModel().getColumn(2).setMaxWidth(180);
            table_sinta.getColumnModel().getColumn(3).setMinWidth(70);
            table_sinta.getColumnModel().getColumn(3).setPreferredWidth(70);
            table_sinta.getColumnModel().getColumn(3).setMaxWidth(70);
            table_sinta.getColumnModel().getColumn(4).setMinWidth(70);
            table_sinta.getColumnModel().getColumn(4).setPreferredWidth(70);
            table_sinta.getColumnModel().getColumn(4).setMaxWidth(70);
        }

        TablaToken.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Token", "Lexema", "Patron", "Linea", "Columna"
            }
        ));
        jScrollPane2.setViewportView(TablaToken);
        if (TablaToken.getColumnModel().getColumnCount() > 0) {
            TablaToken.getColumnModel().getColumn(3).setMinWidth(70);
            TablaToken.getColumnModel().getColumn(3).setPreferredWidth(70);
            TablaToken.getColumnModel().getColumn(3).setMaxWidth(70);
            TablaToken.getColumnModel().getColumn(4).setMinWidth(70);
            TablaToken.getColumnModel().getColumn(4).setPreferredWidth(70);
            TablaToken.getColumnModel().getColumn(4).setMaxWidth(70);
        }

        jScrollPane1.setViewportView(text_editor);

        BTlimpiar.setText("limpiar");
        BTlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTlimpiarActionPerformed(evt);
            }
        });

        BT_anasintactico.setText("Ana Sinta");
        BT_anasintactico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_anasintacticoActionPerformed(evt);
            }
        });

        BT_analizar.setText("Analizar");
        BT_analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_analizarActionPerformed(evt);
            }
        });

        BT_abrir.setText("Abrir");
        BT_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_abrirActionPerformed(evt);
            }
        });

        Tabla_Bloque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Bloque", "Error", "Linea", "Columna"
            }
        ));
        Tabla_Bloque.setRowHeight(120);
        jScrollPane3.setViewportView(Tabla_Bloque);
        if (Tabla_Bloque.getColumnModel().getColumnCount() > 0) {
            Tabla_Bloque.getColumnModel().getColumn(0).setMinWidth(150);
            Tabla_Bloque.getColumnModel().getColumn(0).setPreferredWidth(150);
            Tabla_Bloque.getColumnModel().getColumn(0).setMaxWidth(150);
            Tabla_Bloque.getColumnModel().getColumn(3).setMinWidth(70);
            Tabla_Bloque.getColumnModel().getColumn(3).setPreferredWidth(70);
            Tabla_Bloque.getColumnModel().getColumn(3).setMaxWidth(70);
            Tabla_Bloque.getColumnModel().getColumn(4).setMinWidth(70);
            Tabla_Bloque.getColumnModel().getColumn(4).setPreferredWidth(70);
            Tabla_Bloque.getColumnModel().getColumn(4).setMaxWidth(70);
        }

        BT_Crear.setText("Crear");
        BT_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CrearActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BLOQUES");

        javax.swing.GroupLayout JFondoLayout = new javax.swing.GroupLayout(JFondo);
        JFondo.setLayout(JFondoLayout);
        JFondoLayout.setHorizontalGroup(
            JFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JFondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(501, 501, 501))
            .addGroup(JFondoLayout.createSequentialGroup()
                .addGroup(JFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(JFondoLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(323, 323, 323))
                    .addGroup(JFondoLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(BT_abrir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTlimpiar)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JFondoLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(JFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JFondoLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JFondoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(JFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(JFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BT_analizar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BT_anasintactico, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27))))
            .addGroup(JFondoLayout.createSequentialGroup()
                .addGroup(JFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JFondoLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JFondoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(BT_Crear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JFondoLayout.setVerticalGroup(
            JFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JFondoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(JFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGroup(JFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JFondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JFondoLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(JFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BTlimpiar)
                                    .addComponent(BT_abrir))
                                .addGap(13, 13, 13)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JFondoLayout.createSequentialGroup()
                                .addGroup(JFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(JFondoLayout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(BT_analizar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGroup(JFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JFondoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JFondoLayout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(BT_anasintactico)))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JFondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BT_Crear)
                        .addGap(167, 167, 167))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_analizarActionPerformed
        // TODO add your handling code here:
        analizador_lexico analizador = new analizador_lexico(lista_token);
        analizador.analizar(text_editor.getText());

        DefaultTableModel model = (DefaultTableModel) TablaToken.getModel();
        model.setRowCount(0); // Limpia la tabla
        cote.colorearEditorTexto(text_editor);

        for (Token token : lista_token) {
            model.addRow(new Object[]{
                token.getTipo(),
                token.getLexema(),
                token.getPatron(),
                token.getFila(),
                token.getColumna()
            });
        }
    }//GEN-LAST:event_BT_analizarActionPerformed

    private void BT_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_abrirActionPerformed
        // TODO add your handling code here:
        if (seleccionado.showDialog(null, "Abrir Archivo") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionado.getSelectedFile();
            if (archivo.canRead()) {
                if (archivo.getName().endsWith("txt")) {
                    String contenido = gestion.AbrirATexto(archivo);
                    text_editor.setText(contenido);
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor seleccione un archivo.txt");
                }
            }
        }
    }//GEN-LAST:event_BT_abrirActionPerformed

    private void BTlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTlimpiarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TablaToken.getModel();
        model.setRowCount(0); // Limpia la tabla
        lista_token.clear(); // Limpia la lista
        text_editor.setText("");
        text_editor.setForeground(black);
        DefaultTableModel model2 = (DefaultTableModel) table_sinta.getModel();
        model2.setRowCount(0);
        lista_simbolos.clear();
        DefaultTableModel model3 = (DefaultTableModel) Tabla_Bloque.getModel();
        model3.setRowCount(0);
        lista_bloques.clear();
    }//GEN-LAST:event_BTlimpiarActionPerformed

    private void BT_anasintacticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_anasintacticoActionPerformed
        // TODO add your handling code here:
        analizador_sintactico anasinta = new analizador_sintactico(lista_token);
        anasinta.analizar();
        lista_simbolos.clear();
        DefaultTableModel model2 = (DefaultTableModel) table_sinta.getModel();
        model2.setRowCount(0); // Limpia la tabla

        for (Simbolos sim : anasinta.getListaSimbolos()) {
            lista_simbolos.add(sim);
            model2.addRow(new Object[]{
                sim.getRespuesta(),
                sim.getLexemas(),
                sim.getError(),
                sim.getFilas(),
                sim.getColumnas()
            });
        }
    }//GEN-LAST:event_BT_anasintacticoActionPerformed

    private void BT_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CrearActionPerformed
        // TODO add your handling code here:
        // Verifica que el análisis sintáctico se haya realizado previamente
        if (lista_simbolos != null && !lista_simbolos.isEmpty()) {
            Bucles bucle = new Bucles(lista_simbolos);
            bucle.crear();
            DefaultTableModel model3 = (DefaultTableModel) Tabla_Bloque.getModel();
            model3.setRowCount(0);

            for (Bloques bloq : bucle.getCajaBloque()) {
                model3.addRow(new Object[]{
                    bloq.getBtipo(),
                    bloq.getBloque(),
                    bloq.getBerror(),
                    bloq.getBfila(),
                    bloq.getBcolumna()
                });
            }
        } else {
            JOptionPane.showMessageDialog(this, "Primero realiza el análisis sintáctico antes de crear los bloques.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BT_CrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Crear;
    private javax.swing.JButton BT_abrir;
    private javax.swing.JButton BT_analizar;
    private javax.swing.JButton BT_anasintactico;
    private javax.swing.JButton BTlimpiar;
    private javax.swing.JPanel JFondo;
    private javax.swing.JTable TablaToken;
    private javax.swing.JTable Tabla_Bloque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable table_sinta;
    private javax.swing.JTextPane text_editor;
    // End of variables declaration//GEN-END:variables
}
